routes/web.php
<?php

Route::get('artisan_command',function(){
    // \Artisan::call('migrate --seed');
    // \Artisan::call('config:cache');
    // \Artisan::call('config:clear');
    // \Artisan::call('config:cache');

    echo "Done";
    exit;
});

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Cities
    Route::delete('cities/destroy', 'CityController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CityController');

    // Branches
    Route::delete('branches/destroy', 'BranchController@massDestroy')->name('branches.massDestroy');
    Route::resource('branches', 'BranchController');
    // Route::get('get/state/cities','BranchController@getStateCities')->name('getStateCities');

    // States
    Route::delete('states/destroy', 'StateController@massDestroy')->name('states.massDestroy');
    Route::resource('states', 'StateController');

    // Customers
    Route::delete('customers/destroy', 'CustomerController@massDestroy')->name('customers.massDestroy');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/assign/gas/{cusId}','CustomerController@assignGas')->name('customers.assign_gas');
    Route::get('customers/edit/assign/gas/{assignGID}','CustomerController@editAssignGas')->name('customers.edit.assign_gas');
    Route::post('customers/save/assign/gas','CustomerController@saveAssignGas')->name('customers.save.assign_gas');
    Route::get('customers/delete/assign/gas/{assignGID}','CustomerController@deleteAssignGas');

    // Suppliers
    Route::delete('suppliers/destroy', 'SupplierController@massDestroy')->name('suppliers.massDestroy');
    Route::resource('suppliers', 'SupplierController');
    Route::get('suppliers/assign/gas/{supId}','SupplierController@assignGas')->name('suppliers.assign_gas');
    Route::get('suppliers/edit/assign/gas/{assignGID}','SupplierController@editAssignGas')->name('suppliers.edit.assign_gas');
    Route::post('suppliers/save/assign/gas','SupplierController@saveAssignGas')->name('suppliers.save.assign_gas');
    Route::get('suppliers/delete/assign/gas/{assignGID}','SupplierController@deleteAssignGas');
    

    // Gas
    Route::delete('gas/destroy', 'GasController@massDestroy')->name('gas.massDestroy');
    Route::resource('gas', 'GasController');

    // Cylinder Companies
    Route::delete('cylinder-companies/destroy', 'CylinderCompanyController@massDestroy')->name('cylinder-companies.massDestroy');
    Route::resource('cylinder-companies', 'CylinderCompanyController');

    // Cylinders
    Route::delete('cylinders/destroy', 'CylinderController@massDestroy')->name('cylinders.massDestroy');
    Route::resource('cylinders', 'CylinderController');
    Route::post('cylinders/discontinue', 'CylinderController@cylDiscontinue')->name('cylinders.discontinue');

    // Refilling
    Route::get('cylinder/refilling','RefillingController@index')->name('cylinder.refilling');
    Route::get('cylinder/refilling/create','RefillingController@create')->name('cylinder.refilling.create');
    Route::post('cylinder/refilling/store','RefillingController@store')->name('cylinder.refilling.store');
    Route::get('cylinder/refilling/{id}/edit','RefillingController@edit')->name('cylinder.refilling.edit');
    Route::post('cylinder/refilling/update','RefillingController@update')->name('cylinder.refilling.update');
    Route::delete('cylinder/refilling/destroy/{id}','RefillingController@delete')->name('cylinder.refilling.destroy');
    Route::any('cylinder/refilling/mass/destroy', 'RefillingController@massDestroy')->name('cylinder.refilling.mass.destroy');
    Route::get('cylinder/refilling/{id}','RefillingController@show')->name('cylinder.refilling.show');
    
    Route::get('get/supplier/detail','RefillingController@getSupDetail');
    Route::get('cyl-refi/add_more','RefillingController@addMore');
    Route::get('cylinder/refilling/supplier/gas','RefillingController@getSupplierGas');
    Route::get('cylinder/refilling/gas/cyl_no','RefillingController@getGasCylinder');
    Route::get('delete/refilling_detail','RefillingController@deleteRefillingDetail');

    // Refilling Received
    Route::get('cyl/refilling/received','RefillingReceivedController@index')->name('cyl.refilling.received');
    Route::get('get/supplier/challan','RefillingReceivedController@getSupChal');
    Route::get('get/refilling/list','RefillingReceivedController@refillingList');
    Route::get('change/refilling/status','RefillingReceivedController@changeStatus');

    // Cylinder Issue
    Route::any('cylinder-issue/destroy', 'CylinderIssueController@massDestroy')->name('cylinderIssue.massDestroy');
    Route::resource('cylinder-issue', 'CylinderIssueController');
    Route::get('cyl-issue/add_more','CylinderIssueController@addMore');
    Route::get('cylinder-issue/get/cyl-no','CylinderIssueController@getCylNo');
    Route::get('get/branch/customer','CylinderIssueController@getBranchCus');
    Route::get('get/customer/detail','CylinderIssueController@getCusDetail');
    Route::get('delete/issue_detail','CylinderIssueController@deleteIssueDetail');
    Route::get('cylinder-issue/customer/gas','CylinderIssueController@getCustomerGas');
    Route::get('cylinder-issue/customer/trans','CylinderIssueController@getCustomerTrans');

    // Cylinder Issue Received
    Route::get('cyl-issue/received','IssueReceivedController@index')->name('cylinderIssue.received');
    Route::get('cyl-issue/received/get/challan','IssueReceivedController@getChallan');
    Route::get('get/issued/list','IssueReceivedController@issuedList');
    Route::get('change/issue/status','IssueReceivedController@changeStatus');

    // Income Expenses
    Route::delete('income-expenses/destroy', 'IncomeExpenseController@massDestroy')->name('income-expenses.massDestroy');
    Route::resource('income-expenses', 'IncomeExpenseController');
    Route::get('income-expenses/{type}/add_more','IncomeExpenseController@addMore');
    Route::get('income-expenses/delete/{type}','IncomeExpenseController@deleteIncExp');

    // Purchases
    Route::delete('purchases/destroy', 'PurchaseController@massDestroy')->name('purchases.massDestroy');
    Route::resource('purchases', 'PurchaseController');
    Route::get('purchase/add_more','PurchaseController@addMore');
    Route::get('purchase/download/{id}','PurchaseController@download')->name('purchase.download');
    Route::get('delete/purchase','PurchaseController@deletePurchase');

    // Income Expense Report
    Route::match(['GET','POST'],'report/income-expense','IncomeExpenseController@report')->name('report.income-expense');
    Route::get('report/cylinder/{cusId?}','CylinderController@report')->name('report.cylinder');

    // Invoice
    Route::get('invoice','InvoiceController@index')->name('invoice');
    Route::get('invoice/create','InvoiceController@create')->name('invoice.create');
    Route::get('invoice/customer/detail','InvoiceController@cusDetail');
    Route::get('invoice/get/challan_detail','InvoiceController@challanDetail');
    Route::post('invoice/save','InvoiceController@save')->name('invoice.save');
    Route::get('invoice/delete','InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/view/{invId}','InvoiceController@view')->name('invoice.view');

    Route::match(['get','post'],'invoice/download/{invId?}','InvoiceController@download')->name('invoice.download');

    Route::get('testpdf','InvoiceController@testpdf');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/CylinderIssue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;
use App\Models\Branch;
use App\Models\CylinderCompany;

class CylinderIssue extends Model
{
    use HasFactory,SoftDeletes;

    protected $table = 'cylinder_issue';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'branch_id',
        'cus_id',
        'po_num',
        'po_date',
        'sys_chal_no',
        'delivery_date',
        'veh_no',
        'remark',
        'is_issue_received',
        'trans',
        'total',
        'is_invoice_created',
        'is_rent_invoice_created',
        'address',
        'mob_no'
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public static function setPONum($id){
        $number = sprintf("%03d",$id);
        $code   = substr(strtoupper(config('constant.poNumPrefix')), 0, 3);
        
        return $code.$number;
    }

    public static function setSysChNo($id){
        $number = sprintf("%03d",$id);
        $code   = substr(strtoupper(config('constant.sysChalNoPrefix')), 0, 3);
        
        return $code.$number;
    }

    public static function getBranch($id){
        $branch = Branch::find($id);
        return ($branch)?$branch->name:'';
    }

    public static function getCylCom($id){
        $cylCom = CylinderCompany::find($id);
        return ($cylCom)?$cylCom->name:'';
    }
}

resources/views/admin/cylinderIssue/add_more.blade.php
<tr id="{{'newIssue_'.$count}}">
    <td>
        <select class="form-control gas" name="gas[]" id="{{'gas_'.$count}}">
            <option value="">Select Gas</option>
        </select>
    </td>

    <td>
        <select class="form-control cyl_no" name="cylNo[]" data-id="{{$count}}" id="{{'cyl_'.$count}}">
            <option value="">Select Cylinder No</option>
        </select>
    </td>

    <td>
        <div class="input-group">
            <input type="text" class="form-control allownumericwithdecimal rate" name="rate[]" id="{{'rate_'.$count}}" value="0.00" autocomplete="off" readonly="readonly" />

            <input type="hidden" name="rent[]" id="{{'rent_'.$count}}" value="" />
            <input type="hidden" name="startRent[]" id="{{'srent_'.$count}}" value="" />

            <div class="input-group-append">
                <span class="input-group-text">RS</span>
            </div>
        </div>
    </td>

    <input type="hidden" name="status[]" value="0" />
    <td>
        <button type="button" class="btn btn-danger remove" id="{{$count}}" title="Remove">
            <i class="far fas fa-minus-circle"></i>
        </button>
    </td>
</tr>

resources/views/admin/cylinderIssue/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        {{'Create Cylinder Issue'}}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.cylinder-issue.store") }}" enctype="multipart/form-data" id="cylIssueFrm">
        @csrf
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required">
                            {{'Branch/Distributor'}}
                        </label>
                        <select class="form-control select2 {{ $errors->has('branch_id') ? 'is-invalid' : '' }}" name="branch_id" id="branch_id" >
                            @foreach($branches as $id => $branch)
                                <option value="{{ $id }}" {{ old('branch_id') == $id ? 'selected' : '' }}>{{ $branch }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('branch_id'))
                            <span class="text-danger">{{ 'The branch/distributor field is required.' }}</span>
                        @endif
                        <div id="branchError"></div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required">
                            {{'Customer'}}                            
                        </label>
                        
                        <span class="float-right">
                            <a href="javascript:void(0);" id="cyl_report">
                                <i class="fas fa-file mr-1" title="View Cylinder Report"></i>
                            </a>

                            <a href="javascript:void(0);">
                                <i class="fas fa-eye mr-1" id="view_cus" title="View Customer Detail" data-toggle="modal"></i>
                            </a>
                        </span>

                        <div id="renderCus">
                            @include('admin.cylinderIssue.customer')
                        </div>
                        
                        @if($errors->has('cus_id'))
                            <span class="text-danger">{{ 'The customer field is required.' }}</span>
                        @endif
                        <div id="cusError"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'PO Number'}}
                        </label>
                        
                        <div>
                            <i>{{"Auto Generate"}}</i>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'PO Date'}}
                        </label>
                        
                        <input class="form-control datepick" type="text" name="po_date" id="po_date" value="{{ old('po_date') }}" autocomplete="off" readonly="readonly" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'System Challan No'}}
                        </label>
                        
                        <div>
                            <i>{{"Auto Generate"}}</i> 
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required">
                            {{'Delivery Date'}}
                        </label>
                        <input class="form-control ddate {{ $errors->has('delivery_date') ? 'is-invalid' : '' }}" type="text" name="delivery_date" id="delivery_date" value="{{ old('delivery_date') }}" autocomplete="off" readonly="readonly" />
                        @if($errors->has('delivery_date'))
                            <span class="text-danger">{{ $errors->first('delivery_date') }}</span>
                        @endif
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'Transportation'}}
                        </label>
                        <input class="form-control" type="text" name="trans" id="trans" value="{{ old('trans', '') }}" autocomplete="off" readonly="readonly" />
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'Vehicle No'}}
                        </label>
                        <input class="form-control text-uppercase {{ $errors->has('vehicle_no') ? 'is-invalid' : '' }}" type="text" name="vehicle_no" id="vehicle_no" value="{{ old('vehicle_no', '') }}" autocomplete="off" maxlength="15" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'Mobile Number'}}
                        </label>
                        <input class="form-control" type="text" name="mob_no" id="mob_no" value="{{ old('mob_no', '') }}" autocomplete="off" readonly="readonly" />
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'Address'}}
                        </label>
                        <textarea class="form-control" name="address" id="address" readonly="readonly">{{ old('address') }}</textarea>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{'Remarks'}}
                        </label>
                        <textarea class="form-control" name="remark" id="remark">{{ old('remark') }}</textarea>
                    </div>
                </div>
            </div>

            <hr/>

            <ul>
                @if($errors->has('cylNo.*'))
                    <li>
                        <span class="text-danger">{{ 'The Cylinder No field is required.' }}</span>
                    </li>
                @endif
                
                @if($errors->has('gas.*'))
                    <li>
                        <span class="text-danger">{{ 'The Gas field is required.' }}</span>
                    </li>
                @endif
            </ul>

            <div id="test">
                <input type="hidden" name="rowCount" id="rowCount" value="0" />
                
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-striped table-sm" id="listing">
                            <thead>
                                <tr>
                                    <th scope="col" width="25%">
                                        <center>
                                            Gas<span class="text text-danger">*</span>
                                        </center>
                                    </th>
                                    
                                    <th scope="col" width="40%">
                                        <center>
                                            Cylinder No<span class="text text-danger">*</span>
                                        </center>
                                    </th>
                              
                                    <th scope="col" width="25%">
                                        <center>
                                            Basic Rate
                                        </center>
                                    </th>
                                    
                                    <th scope="col" width="10%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <select class="form-control gas" name="gas[]" id="gas_0">
                                            <option value="">Select Gas</option>
                                        </select>
                                    </td>

                                    <td>
                                        <select class="form-control cyl_no" name="cylNo[]" data-id="0" id="cyl_0">
                                            <option value="">Select Cylinder No</option>
                                        </select>
                                    </td>

                                    <td>
                                        <div class="input-group">
                                            <input type="text" class="form-control allownumericwithdecimal rate" name="rate[]" id="rate_0" value="0.00" autocomplete="off" readonly="readonly" />
                                            
                                            <input type="hidden" name="rent[]" id="rent_0" value="" />
                                            <input type="hidden" name="startRent[]" id="srent_0" value="" />

                                            <div class="input-group-append">
                                                <span class="input-group-text">RS</span>
                                            </div>
                                        </div>
                                    </td>

                                    <input type="hidden" name="status[]" value="0" />
                                    <td>
                                        <button type="button" class="btn btn-warning" id="addMore" title="Add More">
                                            <i class="far fas fa-plus-circle"></i>
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <div class="text text-right mt-2">
                                            <strong>Total</strong>
                                        </div>
                                    </td>
                                    <td >
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="total" id="total" autocomplete="off" value="0.00" readonly="readonly" placeholder="Total" />
                                            
                                            <div class="input-group-append">
                                                <span class="input-group-text">RS</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.cylinder-issue.index')}}" class="btn btn-default">
                    {{ trans('global.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="customer-modal">
    <div class="modal-dialog">
        <div class="modal-content" id="renderCusDetail">
            @include('admin.cylinderIssue.view_cus_detail')
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/cylinder-issue/add_edit.js?'.time())}}" ></script>
@endsection

resources/views/admin/cylinderIssue/index.blade.php
@extends('layouts.admin')

@section('styles')
    <style type="text/css">
        .buttons-select-all,.buttons-select-none{
            display: none;
        }

        table.dataTable tbody td.select-checkbox:before, table.dataTable tbody th.select-checkbox:before{
            display: none;
        }
    </style>
@endsection

@section('content')
@if(session()->has('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
@endif

@if(session()->has('error'))
    <div class="alert alert-danger">
        {{ session()->get('error') }}
    </div>
@endif

<div class="card">
    <div class="card-header">
        <span>
            {{'Cylinder Issue List'}}
        </span>

        @can('cylinder_issue_create')
            <a class="btn btn-success float-right" href="{{route('admin.cylinder-issue.create')}}">
                <i class="fa fa-plus"></i>
            </a>
        @endcan
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover datatable datatable-Customer">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Branch/Distributor
                        </th>
                        <th>
                            Customer
                        </th>
                        <th>
                            PO Number
                        </th>
                        <th>
                            PO Date
                        </th>
                        <th>
                            System Challan No
                        </th>
                        <th>
                            Delivery Date
                        </th>
                        <th width="10%">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($result as $key => $value)
                        <tr data-entry-id="{{ $value->id }}">
                            <td>
                                {{ $value->id ?? '' }}
                            </td>
                            <td>
                                {{ $value->getBranch($value->branch_id) ?? '' }}
                            </td>
                            <td>
                                {{ $value->cname ?? '' }}
                            </td>
                            <td>
                                {{ $value->po_num ?? '' }}
                            </td>
                            <td>
                                @if(!is_null($value->po_date))
                                    {{date('d-m-Y',strtotime($value->po_date))}}
                                @else
                                    {{'-'}}
                                @endif
                            </td>
                            <td>
                                {{ $value->sys_chal_no ?? '' }}
                            </td>
                            <td>
                                {{ date('d-m-Y',strtotime($value->delivery_date)) }}
                            </td>
                            <td>
                                @can('cylinder_issue_show')
                                    <a class="btn btn-xs btn-primary" href="{{route('admin.cylinder-issue.show', $value->id)}}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                @endcan

                                @if(!$value->is_invoice_created)
                                    @can('cylinder_issue_edit')
                                        <a class="btn btn-xs btn-info" href="{{route('admin.cylinder-issue.edit', $value->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    @endcan

                                    @can('cylinder_issue_delete')
                                        <form action="{{ route('admin.cylinder-issue.destroy', $value->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    @endcan
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
$(function () {
    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    
    // @can('cylinder_issue_delete')
    // let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
    // let deleteButton = {
    //     text: deleteButtonTrans,
    //     url: "{{ route('admin.cylinderIssue.massDestroy') }}",
    //     className: 'btn-danger',
    //     action: function (e, dt, node, config) {
    //         var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
    //             return $(entry).data('entry-id')
    //         });

    //         if (ids.length === 0) {
    //             alert('{{ trans('global.datatables.zero_selected') }}')
    //             return
    //         }

    //         if (confirm('{{ trans('global.areYouSure') }}')) {
    //             $.ajax({
    //                 headers: {'x-csrf-token': _token},
    //                 method: 'POST',
    //                 url: config.url,
    //                 data: { ids: ids, _method: 'DELETE' }})
    //                     .done(function () { location.reload() })
    //         }
    //     }
    // }
    // dtButtons.push(deleteButton)
    // @endcan

    $.extend(true, $.fn.dataTable.defaults, {
        orderCellsTop: true,
        order: [[ 0, 'desc' ]],
        pageLength: 10,
    });
    
    let table = $('.datatable-Customer:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
    }); 
})
</script>
@endsection