routes/web.php
<?php

Route::get('artisan_command',function(){
    // \Artisan::call('migrate --seed');
    // \Artisan::call('config:cache');
    // \Artisan::call('config:clear');
    // \Artisan::call('config:cache');

    echo "Done";
    exit;
});

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Cities
    Route::delete('cities/destroy', 'CityController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CityController');

    // Branches
    Route::delete('branches/destroy', 'BranchController@massDestroy')->name('branches.massDestroy');
    Route::resource('branches', 'BranchController');
    // Route::get('get/state/cities','BranchController@getStateCities')->name('getStateCities');

    // States
    Route::delete('states/destroy', 'StateController@massDestroy')->name('states.massDestroy');
    Route::resource('states', 'StateController');

    // Customers
    Route::delete('customers/destroy', 'CustomerController@massDestroy')->name('customers.massDestroy');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/assign/gas/{cusId}','CustomerController@assignGas')->name('customers.assign_gas');
    Route::get('customers/edit/assign/gas/{assignGID}','CustomerController@editAssignGas')->name('customers.edit.assign_gas');
    Route::post('customers/save/assign/gas','CustomerController@saveAssignGas')->name('customers.save.assign_gas');
    Route::get('customers/delete/assign/gas/{assignGID}','CustomerController@deleteAssignGas');

    // Suppliers
    Route::delete('suppliers/destroy', 'SupplierController@massDestroy')->name('suppliers.massDestroy');
    Route::resource('suppliers', 'SupplierController');
    Route::get('suppliers/assign/gas/{supId}','SupplierController@assignGas')->name('suppliers.assign_gas');
    Route::get('suppliers/edit/assign/gas/{assignGID}','SupplierController@editAssignGas')->name('suppliers.edit.assign_gas');
    Route::post('suppliers/save/assign/gas','SupplierController@saveAssignGas')->name('suppliers.save.assign_gas');
    Route::get('suppliers/delete/assign/gas/{assignGID}','SupplierController@deleteAssignGas');
    

    // Gas
    Route::delete('gas/destroy', 'GasController@massDestroy')->name('gas.massDestroy');
    Route::resource('gas', 'GasController');

    // Cylinder Companies
    Route::delete('cylinder-companies/destroy', 'CylinderCompanyController@massDestroy')->name('cylinder-companies.massDestroy');
    Route::resource('cylinder-companies', 'CylinderCompanyController');

    // Cylinders
    Route::delete('cylinders/destroy', 'CylinderController@massDestroy')->name('cylinders.massDestroy');
    Route::resource('cylinders', 'CylinderController');
    Route::post('cylinders/discontinue', 'CylinderController@cylDiscontinue')->name('cylinders.discontinue');

    // Refilling
    Route::get('cylinder/refilling','RefillingController@index')->name('cylinder.refilling');
    Route::get('cylinder/refilling/create','RefillingController@create')->name('cylinder.refilling.create');
    Route::post('cylinder/refilling/store','RefillingController@store')->name('cylinder.refilling.store');
    Route::get('cylinder/refilling/{id}/edit','RefillingController@edit')->name('cylinder.refilling.edit');
    Route::post('cylinder/refilling/update','RefillingController@update')->name('cylinder.refilling.update');
    Route::delete('cylinder/refilling/destroy/{id}','RefillingController@delete')->name('cylinder.refilling.destroy');
    Route::any('cylinder/refilling/mass/destroy', 'RefillingController@massDestroy')->name('cylinder.refilling.mass.destroy');
    Route::get('cylinder/refilling/{id}','RefillingController@show')->name('cylinder.refilling.show');
    
    Route::get('get/supplier/detail','RefillingController@getSupDetail');
    Route::get('cyl-refi/add_more','RefillingController@addMore');
    Route::get('cylinder/refilling/supplier/gas','RefillingController@getSupplierGas');
    Route::get('cylinder/refilling/gas/cyl_no','RefillingController@getGasCylinder');
    Route::get('delete/refilling_detail','RefillingController@deleteRefillingDetail');

    // Refilling Received
    Route::get('cyl/refilling/received','RefillingReceivedController@index')->name('cyl.refilling.received');
    Route::get('get/supplier/challan','RefillingReceivedController@getSupChal');
    Route::get('get/refilling/list','RefillingReceivedController@refillingList');
    Route::get('change/refilling/status','RefillingReceivedController@changeStatus');

    // Cylinder Issue
    Route::any('cylinder-issue/destroy', 'CylinderIssueController@massDestroy')->name('cylinderIssue.massDestroy');
    Route::resource('cylinder-issue', 'CylinderIssueController');
    Route::get('cyl-issue/add_more','CylinderIssueController@addMore');
    Route::get('cylinder-issue/get/cyl-no','CylinderIssueController@getCylNo');
    Route::get('get/branch/customer','CylinderIssueController@getBranchCus');
    Route::get('get/customer/detail','CylinderIssueController@getCusDetail');
    Route::get('delete/issue_detail','CylinderIssueController@deleteIssueDetail');
    Route::get('cylinder-issue/customer/gas','CylinderIssueController@getCustomerGas');
    Route::get('cylinder-issue/customer/trans','CylinderIssueController@getCustomerTrans');

    // Cylinder Issue Received
    Route::get('cyl-issue/received','IssueReceivedController@index')->name('cylinderIssue.received');
    Route::get('cyl-issue/received/get/challan','IssueReceivedController@getChallan');
    Route::get('get/issued/list','IssueReceivedController@issuedList');
    Route::get('change/issue/status','IssueReceivedController@changeStatus');

    // Income Expenses
    Route::delete('income-expenses/destroy', 'IncomeExpenseController@massDestroy')->name('income-expenses.massDestroy');
    Route::resource('income-expenses', 'IncomeExpenseController');
    Route::get('income-expenses/{type}/add_more','IncomeExpenseController@addMore');
    Route::get('income-expenses/delete/{type}','IncomeExpenseController@deleteIncExp');

    // Purchases
    Route::delete('purchases/destroy', 'PurchaseController@massDestroy')->name('purchases.massDestroy');
    Route::resource('purchases', 'PurchaseController');
    Route::get('purchase/add_more','PurchaseController@addMore');
    Route::get('purchase/download/{id}','PurchaseController@download')->name('purchase.download');
    Route::get('delete/purchase','PurchaseController@deletePurchase');

    // Income Expense Report
    Route::match(['GET','POST'],'report/income-expense','IncomeExpenseController@report')->name('report.income-expense');
    Route::get('report/cylinder/{cusId?}','CylinderController@report')->name('report.cylinder');

    // Invoice
    Route::get('invoice','InvoiceController@index')->name('invoice');
    Route::get('invoice/create','InvoiceController@create')->name('invoice.create');
    Route::get('invoice/customer/detail','InvoiceController@cusDetail');
    Route::get('invoice/get/challan_detail','InvoiceController@challanDetail');
    Route::post('invoice/save','InvoiceController@save')->name('invoice.save');
    Route::get('invoice/delete','InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/view/{invId}','InvoiceController@view')->name('invoice.view');

    Route::match(['get','post'],'invoice/download/{invId?}','InvoiceController@download')->name('invoice.download');

    Route::get('testpdf','InvoiceController@testpdf');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/CylinderCompany.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class CylinderCompany extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'cylinder_companies';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'code',
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public static function setSupCode($id){
        $number = sprintf("%03d",$id);
        $code   = substr(strtoupper(config('constant.cylinderCompanyPrefix')), 0, 3);
        
        return $code.$number;
    }
}

app/Http/Controllers/Admin/CylinderCompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCylinderCompanyRequest;
use App\Http\Requests\StoreCylinderCompanyRequest;
use App\Http\Requests\UpdateCylinderCompanyRequest;
use App\Models\CylinderCompany;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Models\State;
use App\Models\City;

class CylinderCompanyController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('cylinder_company_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $cylinderCompanies = CylinderCompany::all();

        return view('admin.cylinderCompanies.index', compact('cylinderCompanies'));
    }

    public function create()
    {
        abort_if(Gate::denies('cylinder_company_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $states   = State::all()->pluck('name','id')->prepend(trans('global.pleaseSelect'), '');
        $cities   = City::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.cylinderCompanies.create',compact('states','cities'));
    }

    public function store(StoreCylinderCompanyRequest $request)
    {
        $cylinderCompany = CylinderCompany::create($request->all());

        $code = CylinderCompany::setSupCode($cylinderCompany->id);
        $cylinderCompany->code = $code;
        $cylinderCompany->save();
        
        return redirect()->route('admin.cylinder-companies.index')->with('success','Cylinder Company Added Successfully!');
    }

    public function edit(CylinderCompany $cylinderCompany)
    {
        abort_if(Gate::denies('cylinder_company_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $states   = State::all()->pluck('name','id')->prepend(trans('global.pleaseSelect'), '');
        $cities   = City::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.cylinderCompanies.edit', compact('cylinderCompany','states','cities'));
    }

    public function update(UpdateCylinderCompanyRequest $request, CylinderCompany $cylinderCompany)
    {
        $cylinderCompany->update($request->all());

        return redirect()->route('admin.cylinder-companies.index')->with('success','Cylinder Company Updated Successfully!');
    }

    public function show(CylinderCompany $cylinderCompany)
    {
        abort_if(Gate::denies('cylinder_company_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $state = State::find($cylinderCompany->state_id);
        $city  = City::find($cylinderCompany->city_id);

        return view('admin.cylinderCompanies.show', compact('cylinderCompany','state','city'));
    }

    public function destroy(CylinderCompany $cylinderCompany)
    {
        abort_if(Gate::denies('cylinder_company_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $cylinderCompany->delete();

        return back()->with('success','Cylinder Company Deleted Successfully!');
    }

    public function massDestroy(MassDestroyCylinderCompanyRequest $request)
    {
        CylinderCompany::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/cylinderCompanies/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.cylinderCompany.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.cylinder-companies.store") }}" enctype="multipart/form-data" id="cyliComFrm">
            @csrf

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>
                            {{ trans('cruds.cylinderCompany.fields.code') }}
                        </label>
                        
                        <div>
                            <i>{{"Auto Generate"}}</i>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required" for="name">{{ trans('cruds.cylinderCompany.fields.name') }}</label>
                        <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" autocomplete="off" />
                        @if($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                        <span class="help-block">{{ trans('cruds.cylinderCompany.fields.name_helper') }}</span>
                    </div>
                </div>
            </div>

            <?php /*
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required" for="mobile_no">{{ trans('cruds.cylinderCompany.fields.mobile_no') }}</label>
                        <input class="form-control allownumericwithoutdecimal {{ $errors->has('mobile_no') ? 'is-invalid' : '' }}" type="text" name="mobile_no" id="mobile_no" value="{{ old('mobile_no', '') }}" autocomplete="off" maxlength="10" />
                        @if($errors->has('mobile_no'))
                            <span class="text-danger">{{ $errors->first('mobile_no') }}</span>
                        @endif
                        <span class="help-block">{{ trans('cruds.cylinderCompany.fields.mobile_no_helper') }}</span>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required" for="address">{{ trans('cruds.cylinderCompany.fields.address') }}</label>
                        <textarea class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" name="address" id="address">{{ old('address') }}</textarea>
                        @if($errors->has('address'))
                            <span class="text-danger">{{ $errors->first('address') }}</span>
                        @endif
                        <span class="help-block">{{ trans('cruds.cylinderCompany.fields.address_helper') }}</span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="pin_code">{{ trans('cruds.cylinderCompany.fields.pin_code') }}</label>
                        <input class="form-control allownumericwithoutdecimal {{ $errors->has('pin_code') ? 'is-invalid' : '' }}" type="text" name="pin_code" id="pin_code" value="{{ old('pin_code', '') }}" autocomplete="off" maxlength="6" />
                        @if($errors->has('pin_code'))
                            <span class="text-danger">{{ $errors->first('pin_code') }}</span>
                        @endif
                        <span class="help-block">{{ trans('cruds.cylinderCompany.fields.pin_code_helper') }}</span>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required" for="state_id">{{ 'State' }}</label>
                        <select class="form-control select2 {{ $errors->has('state_id') ? 'is-invalid' : '' }}" name="state_id" id="state_id" />
                            @foreach($states as $id => $state)
                                <option value="{{ $id }}" {{ old('state_id') == $id ? 'selected' : '' }}>{{ $state }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('state_id'))
                            <span class="text-danger">{{ 'The state field is required.' }}</span>
                        @endif
                        <div id="stateError"></div>
                    </div>
                </div>
            </div>         

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="required" for="city_id">{{ 'City' }}</label>
                        <select class="form-control select2 {{ $errors->has('city_id') ? 'is-invalid' : '' }}" name="city_id" id="city_id" />
                            @if(isset($cities))
                                @foreach($cities as $id => $city)
                                    <option value="{{ $id }}" {{ old('city_id') == $id ? 'selected' : '' }}>{{ $city }}</option>
                                @endforeach
                            @endif
                        </select>
                        @if($errors->has('city_id'))
                            <span class="text-danger">{{ 'The city field is required.' }}</span>
                        @endif
                        <div id="cityError"></div>
                    </div>
                </div>
            </div>
            */ ?>

            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.cylinder-companies.index')}}" class="btn btn-default">
                    {{ trans('global.cancel') }}
                </a>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/cylinder_company/add_edit.js?'.time())}}" ></script>
@endsection

resources/views/admin/cylinderCompanies/index.blade.php
@extends('layouts.admin')
@section('content')

@if(session()->has('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
@endif

@if(session()->has('error'))
    <div class="alert alert-danger">
        {{ session()->get('error') }}
    </div>
@endif

<div class="card">
    <div class="card-header">
        <span>
            {{ trans('cruds.cylinderCompany.title_singular') }} {{ trans('global.list') }}
        </span>

        @can('cylinder_company_create')
            <a class="btn btn-success float-right" href="{{ route('admin.cylinder-companies.create') }}">
                <i class="fa fa-plus"></i>
            </a>
        @endcan
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-CylinderCompany">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.code') }}
                        </th>
                        <!-- <th>
                            {{ trans('cruds.cylinderCompany.fields.name') }}
                        </th> -->
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.mobile_no') }}
                        </th>
                        <th width="13%">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($cylinderCompanies as $key => $cylinderCompany)
                        <tr data-entry-id="{{ $cylinderCompany->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $cylinderCompany->id ?? '' }}
                            </td>
                            <td>
                                {{ $cylinderCompany->code ?? '' }}
                            </td>
                            <td>
                                {{ $cylinderCompany->name ?? '' }}
                            </td>
                            <!-- <td>
                                {{ $cylinderCompany->mobile_no ?? '' }}
                            </td> -->
                            <td>
                                @can('cylinder_company_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.cylinder-companies.show', $cylinderCompany->id) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                @endcan

                                @can('cylinder_company_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.cylinder-companies.edit', $cylinderCompany->id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                @endcan

                                @can('cylinder_company_delete')
                                    <form action="{{ route('admin.cylinder-companies.destroy', $cylinderCompany->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('cylinder_company_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.cylinder-companies.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 10,
  });
  let table = $('.datatable-CylinderCompany:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/cylinderCompanies/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.cylinderCompany.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-info" href="{{ route('admin.cylinder-companies.edit', $cylinderCompany->id) }}">
                    {{ trans('global.back_to_edit') }}
                </a>

                <a class="btn btn-default" href="{{ route('admin.cylinder-companies.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.id') }}
                        </th>
                        <td>
                            {{ $cylinderCompany->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.code') }}
                        </th>
                        <td>
                            {{ $cylinderCompany->code }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.name') }}
                        </th>
                        <td>
                            {{ $cylinderCompany->name }}
                        </td>
                    </tr>

                    <?php /*
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.mobile_no') }}
                        </th>
                        <td>
                            {{ $cylinderCompany->mobile_no }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.address') }}
                        </th>
                        <td>
                            {{ $cylinderCompany->address }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.cylinderCompany.fields.pin_code') }}
                        </th>
                        <td>
                            {{ !is_null($cylinderCompany->pin_code)?$cylinderCompany->pin_code:'-' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ 'State' }}
                        </th>
                        <td>
                            {{ ($state)?$state->name:'-' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ 'City' }}
                        </th>
                        <td>
                            {{ ($city)?$city->name:'-' }}
                        </td>
                    </tr>
                    */ ?>
                    
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-info" href="{{ route('admin.cylinder-companies.edit', $cylinderCompany->id) }}">
                    {{ trans('global.back_to_edit') }}
                </a>
                
                <a class="btn btn-default" href="{{ route('admin.cylinder-companies.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection